FROM python:3.6-stretch

WORKDIR /usr/src/gdtb

COPY requirements.txt /usr/src/gdtb/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

ENTRYPOINT [ "python" ]
CMD [ "wapi.py", "--start-reactor" ]
