version: "3.5"
services:
    adminer:
        image: adminer
        container_name: adminer
        ports:
            - "8081:8080"
    postgres:
        image: postgres:latest
        container_name: postgres
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=mysecretpassword
            - POSTGRES_USER=gdt
            - POSTGRES_PASSWORD=qwerty
            - POSTGRES_DB=gdt_reactor
        volumes:
            - ./_pg_data:/var/lib/postgresql/data
    server:
        build:
            context: .
            dockerfile: Dockerfile.server
        container_name: server
        ports:
            - "8080:8080"
        environment:
            - SERVER_NAME=localhost:8080
            - HOST=localhost
            - PORT=8080
        volumes:
            - ./app:/usr/src/gdtb/app:ro
            - ./connectors:/usr/src/gdtb/connectors:ro
            - ./wapi.py:/usr/src/gdtb/wapi.py:ro
    reactor:
        build:
            context: .
            dockerfile: Dockerfile.reactor
        container_name: reactor
        volumes:
            - ./app:/usr/src/gdtb/app:ro
            - ./connectors:/usr/src/gdtb/connectors:ro
            - ./wapi.py:/usr/src/gdtb/wapi.py:ro
